// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tab-styles/BinderTabs.tsx": () => import("../components/mockups/tab-styles/BinderTabs.tsx"),
  "./components/mockups/tab-styles/NotchedTabs.tsx": () => import("../components/mockups/tab-styles/NotchedTabs.tsx"),
  "./components/mockups/tab-styles/SteppedTabs.tsx": () => import("../components/mockups/tab-styles/SteppedTabs.tsx")
};
